version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: image_moderation_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: image_moderation
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  backend:
    build: ./backend
    container_name: image_moderation_api
    restart: unless-stopped
    ports:
      - "7000:7000"
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/image_moderation?authSource=admin
      - DATABASE_NAME=image_moderation
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 7000 --reload

  frontend:
    build: ./frontend
    container_name: image_moderation_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongodb_data: